### ISSUE TITLE
Launch SDS website

### ISSUE THREAD

**Issue by quietbits** [stellar/stellar-design-system#5]
- [x] Website layout is presentable (https://github.com/stellar/stellar-design-system/pull/26)
- [x] Minimize normalize CSS (https://github.com/stellar/stellar-design-system/pull/27)
- [x] Update palette colors (https://github.com/stellar/stellar-design-system/pull/28)

**Comment by shanzzam** [comment]
I'd add internal announcement as well. How about we demo this at engineering all-hands June 17?
