### ISSUE TITLE
Feature Request: Pie Progress Indicator

### ISSUE THREAD

**Issue by cbshin-stellar** [stellar/stellar-design-system#63]
### What problem does your feature solve?
We need a progress indicator for the Anchor Validator to show progress/status of SEP tests run.

### What would you like to see?
**Indicator logic:**
Pie Circle / Number of Tests
Then progressing in clockwise order, showing each slice (representative of each test) as green for successful, or red for unsuccessful. These colors can be pulled from the current color palette for light/dark mode

Link to designs:
https://www.figma.com/file/4BjIB3QZMbI5pd87JJwSLi/Anchor-Validator?node-id=395%3A62

**Comment by shanzzam** [comment]
What's the interface with this component? There's a need to show real-time loading indication for each slice.
