### ISSUE TITLE
Feature Request: Color palette in SDS Website

### ISSUE THREAD

**Issue by piyalbasu** [stellar/stellar-design-system#65]
It'd be useful to be able to see every available color on the SDS website.

For ex: `var(--pal-brand-primary)` next to a swatch of what that color looks like

Issue it solves: when a dev receives a comment like "Let's make this color stand out more", we could take a look at what's available in our color palette to use

**Comment by quietbits** [comment]
SDS v3 has a color palette on the [website](https://design-system-pr208.previews.kube001.services.stellar-ops.com/colors).
